# Generated by Django 4.0.6 on 2022-11-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qn', '0004_question_ans'),
    ]

    operations = [
        migrations.AddField(
            model_name='stud',
            name='is_active',
            field=models.IntegerField(default=0),
        ),
    ]
