# Generated by Django 4.0.6 on 2022-12-29 07:58

from django.db import migrations, models
import qn.models


class Migration(migrations.Migration):

    dependencies = [
        ('qn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='qn',
            field=models.ImageField(null=True, upload_to=qn.models.upload_path),
        ),
    ]
