# Generated by Django 4.0.6 on 2022-12-29 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qn', '0002_alter_question_qn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='qn',
            field=models.TextField(null=True),
        ),
    ]
