# Generated by Django 4.0.6 on 2022-11-04 03:45

from django.db import migrations, models
import qn.models


class Migration(migrations.Migration):

    dependencies = [
        ('qn', '0002_result_login_result_logout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='ans',
            new_name='qnno',
        ),
        migrations.RemoveField(
            model_name='question',
            name='A',
        ),
        migrations.RemoveField(
            model_name='question',
            name='B',
        ),
        migrations.RemoveField(
            model_name='question',
            name='C',
        ),
        migrations.RemoveField(
            model_name='question',
            name='D',
        ),
        migrations.RemoveField(
            model_name='question',
            name='qstnno',
        ),
        migrations.AlterField(
            model_name='question',
            name='qn',
            field=models.ImageField(blank=True, null=True, upload_to=qn.models.upload_path),
        ),
    ]
