# Generated by Django 4.0.6 on 2022-11-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qn', '0003_rename_ans_question_qnno_remove_question_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='ans',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
