# Generated by Django 4.0.6 on 2023-01-02 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qn', '0005_alter_question_qn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='qn',
            field=models.TextField(blank=True, null=True),
        ),
    ]
