# Generated by Django 4.0.6 on 2023-01-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qn', '0006_alter_question_qn'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stud',
            name='test',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
