# Generated by Django 4.0.6 on 2023-01-18 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qn', '0007_question_status_stud_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testid', models.CharField(max_length=20, null=True)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
    ]
