# Generated by Django 4.0.6 on 2023-01-18 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qn', '0008_tests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='status',
        ),
    ]
